<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit82764b9e9265249c23fdb5ef1d6445cd
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OpenCage\\Geocoder\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OpenCage\\Geocoder\\' => 
        array (
            0 => __DIR__ . '/..' . '/opencage/geocode/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit82764b9e9265249c23fdb5ef1d6445cd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit82764b9e9265249c23fdb5ef1d6445cd::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
