<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5738b5fe80d48915fc86c313d43429ac
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Recombee\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Recombee\\' => 
        array (
            0 => __DIR__ . '/..' . '/recombee/php-api-client/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Requests' => 
            array (
                0 => __DIR__ . '/..' . '/rmccue/requests/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5738b5fe80d48915fc86c313d43429ac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5738b5fe80d48915fc86c313d43429ac::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit5738b5fe80d48915fc86c313d43429ac::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
